export const IMAGE={
    heart_eye:require("../assets/images/heart-eyes.png"),
    MAskGroup:require("../assets/images/MaskGroup.png"),
    Mail:require("../assets/images/mail.png"),
    Lock:require("../assets/images/lock.png"),
    visibility:require("../assets/images/visibility.png"),
    visibility_off :require("../assets/images/visibility_off.png"),
    Home :require("../assets/images/Home.png"),
    OnlineQuotation :require("../assets/images/OnlineQuotation.png"),
    Contact :require("../assets/images/Contact.png"),
    MyAccount :require("../assets/images/MyAccount.png"),
    Waving_hand:require("../assets/images/waving_hand.png"),
    Seating:require("../assets/images/Seating.png"),
    Background:require("../assets/images/Background.png"),
    Keyboard_backspace:require("../assets/images/keyboard_backspace.png"),
    box:require("../assets/images/box.png"),
    document:require("../assets/images/document.png"),
    RadioButton_on:require("../assets/images/RadioButton_on.png"),
    RadioButton_off:require("../assets/images/RadioButton_off.png"),
    arrow:require("../assets/images/arrow.png"),
    Search:require("../assets/images/Search.png"),
    formula1:require("../assets/images/formula1.png"),
    formula2:require("../assets/images/formula2.png"),
    formula3:require("../assets/images/formula3.png"),
    arrowBlue:require("../assets/images/arrowBlue.png"),
    ellipse:require("../assets/images/Ellipse.png"),
    Rectangle_dot:require("../assets/images/Rectangle_box.png"),
    up_arrow:require("../assets/images/upload.png"),
    dune_arrow:require("../assets/images/dropdown.png"),
    Line:require("../assets/images/Line.png"),
    backgroundOfContact:require("../assets/images/BackgrounfOfContact.png"),
    email:require("../assets/images/email.png"),
    call:require("../assets/images/contactbrown.png"),
    support:require("../assets/images/custmarSuport.png"),
    accountFile:require("../assets/images/accountFile.png"),
    Subscribe:require("../assets/images/Subscribe.png"),
    editLogo:require("../assets/images/editLogo.png"),
    edit:require("../assets/images/edit.png"),
    file_download:require("../assets/images/file_download.png"),
    CheckButton:require("../assets/images/CheckButton.png"),
    unCheckedButton:require("../assets/images/unCheckedButton.png"),
    editIcon:require("../assets/images/editIcon.png"),
    RectangleStep:require("../assets/images/Rectanglestep.png"),
    Calender:require("../assets/images/calendar.png"),


}           